[ -f "/home/max/.ghcup/env" ] && . "/home/max/.ghcup/env" # ghcup-env
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"
zstyle ':omz:update' mode auto      # update automatically without asking

# DISABLE_LS_COLORS="true"

HIST_STAMPS="yyyy-mm-dd"
plugins=(git)

source $ZSH/oh-my-zsh.sh

export MANPATH="/usr/local/man:$MANPATH"

export LANG=en_US.UTF-8

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

export ARCHFLAGS="-arch $(uname -m)"

alias ls='ls --color=tty'
alias start='start-hyprland'

set -o vi

source <(fzf --zsh)

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

update()
{
	sudo pacman -Syu
}

alias ss='slurp | grim -g - - | wl-copy'

connect(){
  kitty +kitten ssh myserver
}

reload(){
  kill -SIGUSR1 $KITTY_PID
}


